name: LVS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "lvs"
  cancel-in-progress: true

jobs:
  lvs:
    runs-on: ubuntu-latest
    container:
      image: wulffern/aicex:24.04_0.1.4
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: LVS
        uses: analogicus/jnw-lvs-action@main
        with:
          cell: "CNR_GR02"
          library: "CNR_GR02_SKY130NM"
